---
name: open_source
full_name: Open Source Working Group
type: docs
owner_type: "working-group"
status: active
testable: false
description: >
  We support 18F better practicing and implementing open source.  
stage: live
licenses:
  wg-open_source:
    name: Public Domain (CC0)
    url: https://creativecommons.org/publicdomain/zero/1.0/ 
links:
- url: https://pages.18f.gov/open-source-guide/
  text: 18F Open Source Guide
- url: https://pages.18f.gov/open-source-program/
  text: 18F Open Source Program
- url: https://github.com/18F/open-source-policy
  text: 18F Open Source Policy  
team:
- github: brittag
  role: lead
- github: adrianwebb
  role: lead
- github: gbinal
- github: afeld
